global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'maptrack_bot'
    static_configs:
      - targets: ['bot:8000']
    scrape_interval: 15s
    metrics_path: /metrics



